version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: app
      dockerfile: ./Dockerfile
    image: laravel-postgres
    container_name: laravel-app-postgres
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
    networks:
      - laravel-app

  db:
    image: postgres:13.1
    container_name: laravel-app-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel-app
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
    networks:
      - laravel-app

  nginx:
    image: nginx:alpine
    container_name: laravel-app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-app

networks:
  laravel-app:
    driver: bridge